import i18next from "i18next";
import ar from "./navigation-i18n/ar";
import en from "./navigation-i18n/en";
import fa from "./navigation-i18n/fa";
import { authRoles } from "../auth";

i18next.addResourceBundle("en", "navigation", en);
i18next.addResourceBundle("fa", "navigation", fa);
i18next.addResourceBundle("ar", "navigation", ar);

const navigationConfig = [
  {
    id: "dashboard-component",
    title: "Dashboard",
    translate: "DASHBOARD",
    type: "item",
    icon: "material-outline:dashboard",
    url: "dashboard",
  },
  {
    id: "sell-managment-component",
    title: "Sales Management",
    translate: "SALES_MANAGMENT",
    type: "collapse",
    icon: "heroicons-outline:shopping-cart",
    children: [
      {
        id: "temporary-registration",
        title: "Temporary Registration",
        translate: "TEMPORARY_REGISTRATION",
        type: "item",
        url: "trade/temporarysubmit",
        end: true,
        target: "_blank",
      },
      // {
      //   id: "buy-flight",
      //   title: "Buy Flight",
      //   translate: "BUY_FLIGHT",
      //   type: "link",
      //   url: "https://savosh.com/trade/flights",
      //   end: true,
      //   target: "_blank",
      // },
      {
        id: "online-ticket",
        title: "Online Ticket",
        translate: "ONLINE_TICKET",
        type: "item",
        url: "trade/online-ticket",
        end: true,
        target: "_blank",
      },
      {
        id: "trade-managment",
        title: "Trade Managment",
        translate: "TRADE_MANAGMENT",
        type: "item",
        url: "trade/list",
        end: true,
        target: "_blank",
      },
      {
        id: "cost-and-benefit",
        title: "Cost And Benefit",
        translate: "COST_AND_BENEFIT",
        type: "item",
        url: "trade/cost-benefit",
        end: true,
      },
      // {
      //   id: "cost-and-benefit",
      //   title: "Cost And Benefit",
      //   translate: "COST_AND_BENEFIT",
      //   type: "link",
      //   url: "https://savosh.com/trade/cost-benefit",
      //   end: true,
      //   target: "_blank",
      // },
    ],
  },
  {
    id: "receives-pays-component",
    title: "Receives And Pays",
    translate: "RECEIVES_AND_PAYS",
    type: "collapse",
    icon: "material-twotone:open_in_full",
    children: [
      {
        id: "receives-cash",
        title: "Receives Cash",
        translate: "RECEIVES_CASH",
        type: "item",
        url: "credit-debit/credit-cashdesk",
        end: true,
        target: "_blank",
      },
      {
        id: "payss-cash",
        title: "Pays Cash",
        translate: "PAYS_CASH",
        type: "item",
        url: "credit-debit/debit-cashdesk",
        end: true,
        target: "_blank",
      },
      {
        id: "Current-payments",
        title: "Current Payments",
        translate: "CURRENT_PAYMENTS",
        type: "link",
        url: "https://savosh.com/credit-debit/current",
        end: true,
        target: "_blank",
      },
      {
        id: "Management_of-receipts",
        title: "Management Of Receipts",
        translate: "MANAGEMENT_OF_RECEIPTS",
        type: "link",
        url: "https://savosh.com/credit-debit/credit/list",
        end: true,
        target: "_blank",
      },
      {
        id: "Manage-payments",
        title: "Manage payments",
        translate: "MANAGE_PAYMENTS",
        type: "link",
        url: "https://savosh.com/credit-debit/debit/list",
        end: true,
        target: "_blank",
      },
      {
        id: "cheque-operation",
        title: "cheque Operation",
        translate: "CHEQUE_OPERATION",
        type: "link",
        url: "https://savosh.com/credit-debit/check-operation",
        end: true,
        target: "_blank",
      },
      {
        id: "Account_summary",
        title: "Account Summary",
        translate: "Account_Summary",
        type: "link",
        url: "https://savosh.com/credit-debit/summary/preference",
        end: true,
        target: "_blank",
      },
    ],
  },
  {
    id: "salary",
    title: "Salary",
    translate: "SALARY",
    type: "collapse",
    icon: "heroicons-outline:calendar",
    children: [
      {
        id: "traffic_control_of_people",
        title: "Traffic Control Of People",
        translate: "TRAFFIC_CONTROL_PROPLE",
        type: "link",
        url: "https://savosh.com/salary",
        end: true,
        target: "_blank",
      },
    ],
  },

  {
    id: "Basic-definitions",
    title: "Basic Definitions",
    translate: "BASIC_DEFINITIONS",
    type: "collapse",
    icon: "heroicons-outline:database",
    children: [
      {
        id: "Tree-of-accounts",
        title: "Tree Of Accounts",
        translate: "TREE_OF_ACCOUNTS",
        type: "link",
        url: "https://savosh.com/accounting/treeview",
        end: true,
        target: "_blank",
      },
      {
        id: "Payment-type",
        title: "Payment Type",
        translate: "PAYMENT_TYPE",
        type: "link",
        url: "https://savosh.com/accounting/settings/trade/checkouts",
        end: true,
        target: "_blank",
      },
      {
        id: "Definition-of-income",
        title: "Definition Of Income",
        translate: "DEFINITION_OF_INCOME",
        type: "link",
        url: "https://savosh.com/accounting/settings/trade/income",
        end: true,
        target: "_blank",
      },
      {
        id: "Transaction-type",
        title: "Transaction Type",
        translate: "TRANSACTION_TYPE",
        type: "link",
        url: "https://savosh.com/accounting/settings/trade/type",
        end: true,
        target: "_blank",
      },
    ],
  },
  {
    id: "customers-department-component",
    title: "Customers Department",
    translate: "CUSTOMERS_DEPARTMENT",
    type: "collapse",
    icon: "material-outline:people_alt",
    children: [
      {
        id: "customers",
        title: "Customers",
        translate: "CUSTOMERS",
        type: "item",
        url: "customers-department/customers",
        end: true,
      },
      {
        id: "call-control-center",
        title: "Call Control Center",
        translate: "Call_CONTROL_CENTER",
        type: "link",
        url: "https://savosh.com/customers/callcenter",
        end: true,
        target: "_blank",
      },
      {
        id: "communication-services",
        title: "Communication Services",
        translate: "COMMUNICATION_SERVICES",
        type: "link",
        url: "https://mehromah24.com/dashboard",
        end: true,
        target: "_blank",
      },
    ],
  },
  {
    id: "Organizational-department",
    title: "Organizational Department",
    translate: "ORGANIZATIONAL_DEPARTMENT",
    type: "collapse",
    icon: "heroicons-outline:office-building",
    children: [],
  },
  {
    id: "administrative-department",
    title: "Administrative department",
    translate: "ADMINISTRATIVE_DEPARTMENT",
    type: "collapse",
    icon: "heroicons-outline:cube",
    children: [
      {
        id: "personnel",
        title: "Personnel",
        translate: "PERSONNEL",
        type: "link",
        url: "https://savosh.com/official/personnel",
        end: true,
        target: "_blank",
      },
      {
        id: "traffic-permits",
        title: "Traffic Permits",
        translate: "TRAFFIC_PERMITS",
        type: "link",
        url: "https://savosh.com/official/rollcall/licenses",
        end: true,
        target: "_blank",
      },
      {
        id: "network-manager",
        title: "Network Manager",
        translate: "NETWORK_MANAGER",
        type: "link",
        url: "https://savosh.com/official/networks",
        end: true,
        target: "_blank",
      },
    ],
  },
  {
    id: "Associates-Department",
    title: "Associates Department",
    translate: "ASSOCIATES_DEPARTMENT",
    type: "collapse",
    icon: "heroicons-outline:view-grid",
    children: [
      {
        id: "Organizational-colleagues",
        title: "Organizational Colleagues",
        translate: "ORGANIZATIONAL_COLLEAGUES",
        type: "link",
        url: "https://savosh.com/colleagues/list",
        end: true,
        target: "_blank",
      },
      {
        id: "Announcements",
        title: "Announcements",
        translate: "ANNOUNCEMENTS",
        type: "link",
        url: "https://savosh.com/colleagues/announcement",
        end: true,
        target: "_blank",
      },
    ],
  },
  // {
  //   id: "reports",
  //   title: "Reports",
  //   translate: "REPORTS",
  //   type: "collapse",
  //   icon: "heroicons-outline:chart-pie",
  //   children: [
  //     {
  //       id: "Call-reports",
  //       title: "Call Reports",
  //       translate: "CALL_REPORTS",
  //       type: "link",
  //       url: "https://savosh.com/reports/calls",
  //       end: true,
  //       target: '_blank'
  //     },
  //     {
  //       id: "Salary-reports",
  //       title: "Salary reports",
  //       translate: "SALARY_REPORTS",
  //       type: "link",
  //       url: "https://savosh.com/reports/salary",
  //       end: true,
  //       target: '_blank'
  //     },

  //     {
  //       id: "Entry-and-exit-reports",
  //       title: "Entry And Exit Reports",
  //       translate: "ENTRY_AND_EXIT_REPORTS",
  //       type: "link",
  //       url: "https://mehromah24.com/dashboard",
  //       end: true,
  //       target: '_blank'
  //     },
  //      {
  //       id: "Sales-detail-reports",
  //       title: "Sales Detail Reports",
  //       translate: "SALES_DETAIL_REPORTS",
  //       type: "link",
  //       url: "https://savosh.com/reports/salary",
  //       end: true,
  //       target: '_blank'
  //     },
  //     {
  //       id: "Activity-reports",
  //       title: "Activity Reports",
  //       translate: "ACTIVITY_REPORTS",
  //       type: "link",
  //       url: "https://mehromah24.com/dashboard",
  //       end: true,
  //       target: '_blank'
  //     },
  //     {
  //       id: "System-crash-reports",
  //       title: "System Crash Reports",
  //       translate: "SYSTEM_CRASH_REPORTS",
  //       type: "link",
  //       url: "https://savosh.com/official/reports/system",
  //       end: true,
  //       target: '_blank'
  //     },
  //   ],
  // },
  {
    id: "Administrative-settings",
    title: "Administrative Settings",
    translate: "ADMINISTRATIVE_SETTINGS",
    type: "collapse",
    icon: "material-solid:settings",
    children: [
      {
        id: "Basic-settings",
        title: "Basic Settings",
        translate: "BASIC_SETTINGS",
        type: "link",
        url: "https://savosh.com/settings/base",
        end: true,
        target: "_blank",
      },
      {
        id: "Management-of-hotels",
        title: "Management Of Hotels",
        translate: "MANAGEMENT_OF_HOTELS",
        type: "link",
        url: "https://savosh.com/settings/hotels",
        end: true,
        target: "_blank",
      },
      {
        id: "Management-of-airports",
        title: "Management Of Airports",
        translate: "MANAGMENT_OF_AIRPORTS",
        type: "link",
        url: "https://savosh.com/settings/airports",
        end: true,
        target: "_blank",
      },
      {
        id: "Airlines-management",
        title: "Airlines Management",
        translate: "AIRLINES_MANAGEMENT",
        type: "link",
        url: "https://savosh.com/settings/airlines",
        end: true,
        target: "_blank",
      },
      {
        id: "Aircraft-management",
        title: "Aircraft Management",
        translate: "AIRVRAFT_MANAGEMENT",
        type: "link",
        url: "https://savosh.com/settings/aircrafts",
        end: true,
        target: "_blank",
      },
      {
        id: "Management-of-countries",
        title: "Management Of Countries",
        translate: "MANAGMENT_OF_COUNTRIES",
        type: "link",
        url: "https://savosh.com/settings/countries",
        end: true,
        target: "_blank",
      },

      {
        id: "Management-of-provinces",
        title: "Management Of Provinces",
        translate: "MANAGMENT_OF_PROVINCES",
        type: "link",
        url: "https://savosh.com/settings/states",
        end: true,
        target: "_blank",
      },
      {
        id: "Management-of-cities",
        title: "Management Of Cities",
        translate: "MANAGMENT_OF_CITIES",
        type: "link",
        url: "https://savosh.com/settings/cities",
        end: true,
        target: "_blank",
      },
    ],
  },
];

export default navigationConfig;
